before_script:
  - poetry install

stages:
  - check
  - deploy

.check:
  stage: check

check/linux:
  extends: .check
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=same-as-branch --profile gcc8-release
    - poetry run python run-ci.py build-and-test

check/macos:
  extends: .check
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=same-as-branch --profile macos-release
    - poetry run python run-ci.py build-and-test

check/windows:
  extends: .check
  tags: [windows]
  script:
    - $env:GOARCH=386
    - $env:CGO_ENABLED=1
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=same-as-branch --profile mingw32-release
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test

.check-deployed:
  stage: check
  when: manual

check/deployed-linux:
  extends: .check-deployed
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=deployed --profile gcc8-release
    - poetry run python run-ci.py build-and-test
  artifacts:
    paths:
      - core/cgo_linux_amd64.go
      - core/ctanker/linux-amd64/include
      - core/ctanker/linux-amd64/lib

check/deployed-macos:
  extends: .check-deployed
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=deployed --profile macos-release
    - poetry run python run-ci.py build-and-test
  artifacts:
    paths:
      - core/cgo_darwin_amd64.go
      - core/ctanker/darwin-amd64/include
      - core/ctanker/darwin-amd64/lib

check/deployed-windows:
  extends: .check-deployed
  tags: [windows]
  script:
    - $env:GOARCH=386
    - $env:CGO_ENABLED=1
    - poetry run python run-ci.py --isolate-conan-user-home install-deps --use-tanker=deployed --profile mingw32-release
    - poetry run python run-ci.py build-and-test
  artifacts:
    paths:
      - core/cgo_windows_386.go
      - core/ctanker/windows-386/include
      - core/ctanker/windows-386/lib

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags
    - master
    - /\Afeat\/.+\z/   # feat/ branches
  except:
    - schedules
  script:
    - poetry run python run-ci.py  mirror

deploy:
 stage: deploy
 when: manual
 tags: [linux]
 script:
  - poetry run python run-ci.py deploy --version $VERSION
