[version]
current = "2.2.0-beta1"

regex = '''
  (2.2.0-beta1)
  |
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "core/core.go"
search = 'currentVersion := "{current_version}"'
